{
  // VSCode app (editor, explorer, files, terminal, workbench, window) settings
  "editor.formatOnSave": true,
  "editor.minimap.enabled": false,
  "editor.inlineSuggest.enabled": true,
  "editor.cursorBlinking": "phase",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.fontFamily": "'FiraCode Nerd Font', monospace",
  "editor.bracketPairColorization.enabled": true,
  "editor.fontLigatures": true,
  "editor.smoothScrolling": true,
  "editor.cursorSmoothCaretAnimation": true,
  "explorer.confirmDragAndDrop": false,
  "explorer.openEditors.visible": 0,
  "explorer.compactFolders": false,
  "files.autoGuessEncoding": true,
  "terminal.integrated.defaultProfile.linux": "zsh",
  "terminal.integrated.fontFamily": "'FiraCode Nerd Font', monospace",
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.cursorStyle": "underline",
  "workbench.colorTheme": "One Dark Pro Darker",
  "workbench.iconTheme": "material-icon-theme",
  "workbench.list.smoothScrolling": true,
  "workbench.sideBar.location": "right",
  "workbench.startupEditor": "none",
  "window.dialogStyle": "custom",
  "window.titleBarStyle": "custom",
  "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
  "window.titleSeparator": "︱",
  "workbench.tips.enabled": false,
  "window.menuBarVisibility": "toggle",
  "window.zoomLevel": -1,
  // Git settings
  "git.autofetch": true,
  "git.fetchOnPull": true,
  // Language settings
  "[php]": {
      "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
  },
  // Extension settings
  "discord.detailsEditing": "📝 {file_name} | {file_size}",
  "discord.detailsDebugging": "🐛 {file_name} | {file_size}",
  "discord.detailsIdling": "💤 | Idling",
  "discord.lowerDetailsEditing": "📂 {workspace}",
  "discord.lowerDetailsDebugging": "📂 {workspace}",
  "discord.lowerDetailsIdling": "{empty}",
  "discord.lowerDetailsNoWorkspaceFound": "❌ No Workspace",
  "discord.largeImage": "{Lang} File",
  "discord.largeImageIdling": "💤 | Idle",
  "discord.removeRemoteRepository": true,
  "github.codespaces.showPerformanceExplorer": true,
  "redhat.telemetry.enabled": false,
  // Prettier settings
  "prettier.arrowParens": "avoid",
  "prettier.printWidth": 120,
  "prettier.singleQuote": true,
  "prettier.tabWidth": 4,
  // Other settings
  "php.suggest.basic": false,
  "npm.packageManager": "yarn",
  "git.enableCommitSigning": true,
  "svelte.enable-ts-plugin": true,
  "javascript.updateImportsOnFileMove.enabled": "always"
}
